server:
  image: backflow/ngrok-docker

  ports:
    - "8082:80"
    - "4432:443"
    - "4443:4443"

  volumes:
    - /opt/ngrok:/ngrok:ro

  environment:
    - domain="ngrok.hunan.fit"

  command: /bin/sh /server.sh
